version: "3"

services:

  rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbit
        ports:
        - "5000:5000"

  flask:
    build: ./Flask
    depends_on:
      - rabbitmq
  
  commanditaire:
    build: ./Commanditaire
    depends_on:
      - rabbitmq
      - flask
    links:
      - rabbitmq
      - flask
  
  worker:
    build: ./Worker
    depends_on:
      - rabbitmq
      - flask
    links:
      - rabbitmq
      - flask
      - commanditaire
